In [54]:
import tensorflow as tf

### Variable in tensorflow

In [55]:
string = tf.Variable("My name is Yogesh",tf.string);
number = tf.Variable(45,tf.int16)
floating = tf.Variable(3.567,tf.float64) 

### Rank in tensorflow

In [56]:
rank1_tensor = tf.Variable(['test'],tf.string)
rank2_tensor = tf.Variable([['ok','ok','ok'],['Yogesh','Yogesh','Yogesh']])

In [57]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### Shape of tensor 

In [58]:
rank2_tensor.shape

TensorShape([2, 3])

### Reshaping the Tensor

In [59]:
demo_tensor = tf.ones([1,2,3])
demo_tensor

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [60]:
reshaped1_tensor = tf.reshape(demo_tensor,[2,3,1])
reshaped1_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [61]:
reshaped2_tensor = tf.reshape(demo_tensor,[3,-1])
reshaped2_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>